# Wicci Project; module makefile; requires GNU Make.
# Copyright (c) 2005 - 2010, J. Greg Davidson, all rights reserved.
# Not to be copied nor shown to anyone without my permission in writing.

include ../Makefile.wicci
vpath %.sql /usr/local/pgsql/share/contrib
all: $(DepMakes) $(SchemaOut)
include $(DepMakes)
