# Wicci Project C Utilities Makefile; requires GNU Make.
# Copyright (c) 2005-2009, J. Greg Davidson.
# You may use this file under the terms of the
# GNU AFFERO GENERAL PUBLIC LICENSE 3.0
# as specified in the file LICENSE.md included with this distribution.
# All other use requires my permission in writing.

# Missing: *-test.c files!!
# all: run-array-test run-str-test run-fmt-test run-this-tag-test run-last-tag-test
#array-test: array-test.c array.h
#run-array-test: array-test
#	array-test
#str-test: str-test.c str.h
#run-str-test: str-test
#	str-test
#fmt-test: fmt-test.c fmt.h
#run-fmt-test: fmt-test
#	fmt-test
#this-tag-test: this-tag-test.c this-tag.h
#run-this-tag-test: this-tag-test
#	this-tag-test
#last-tag-test: last-tag-test.c last-tag.h
#run-last-tag-test: last-tag-test
#	last-tag-test
all:
clean:
	rm -f *.o *-test *.log
